apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: k8s-mongo
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000