apiVersion: apps/v1
kind: Deployment
metadata:
  name: qnotes-deployment
  namespace: qnotes-backend
  labels:
    app: qnotes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: qnotes
  template:
    metadata:
      labels:
        app: qnotes
    spec:
      containers:
      - name: qnotes
        image: rulzz35/qnotes:1.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: qnotes-secret
              key: mongo-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qnotes-secret
              key: mongo-password
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: qnotes-secret
              key: access-token
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: qnotes-secret
              key: refresh-token
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: qnotes-secret
              key: google-client-id
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: qnotes-secret
              key: google-client-secret
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: qnotes-secret
              key: github-client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: qnotes-secret
              key: github-client-secret
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: qnotes-config
              key: environment
        - name: GOOGLE_CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: qnotes-config
              key: google-callback-url
        - name: GITHUB_CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: qnotes-config
              key: github-callback-url
        - name: CLIENT_URL_DEV
          valueFrom:
            configMapKeyRef:
              name: qnotes-config
              key: client-url-dev
        - name: SERVER_URL_DEV
          valueFrom:
            configMapKeyRef:
              name: qnotes-config
              key: server-url-dev
