apiVersion: v1
kind: Service
metadata:
  name: qnotes-service
  namespace: qnotes-backend
spec:
  type: NodePort
  selector:
    app: qnotes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      NodePort: 32000